"""Seed data for MasteryFlow: 10 Concepts, DAG prerequisites, 50 rich questions,
misconception-tagged wrong options, and 3-level progressive hints.
"""

from typing import List, Dict, Any

SEED_CONCEPTS: List[Dict[str, Any]] = [
    {
        "id": "fraction_basics",
        "name": "Fraction Basics",
        "description": "Understanding numerators, denominators, and parts of a whole.",
        "domain": "fractions",
        "tier": 1,
        "prerequisites": [],
    },
    {
        "id": "equivalent_fractions",
        "name": "Equivalent Fractions",
        "description": "Finding and simplifying fractions representing the exact same proportion.",
        "domain": "fractions",
        "tier": 2,
        "prerequisites": ["fraction_basics"],
    },
    {
        "id": "comparing_fractions",
        "name": "Comparing Fractions",
        "description": "Ordering and comparing fractions using common denominators and benchmark fractions.",
        "domain": "fractions",
        "tier": 3,
        "prerequisites": ["equivalent_fractions"],
    },
    {
        "id": "fraction_operations",
        "name": "Fraction Operations",
        "description": "Addition, subtraction, multiplication, and division of fractions with like and unlike denominators.",
        "domain": "fractions",
        "tier": 3,
        "prerequisites": ["equivalent_fractions"],
    },
    {
        "id": "decimals_basics",
        "name": "Decimals Basics",
        "description": "Decimal place value (tenths, hundredths, thousandths) and decimal-fraction conversion.",
        "domain": "decimals",
        "tier": 1,
        "prerequisites": [],
    },
    {
        "id": "ratios",
        "name": "Ratios & Rates",
        "description": "Part-to-part and part-to-whole relationships, language and representations of ratios.",
        "domain": "ratios",
        "tier": 4,
        "prerequisites": ["comparing_fractions", "fraction_operations"],
    },
    {
        "id": "unit_rates",
        "name": "Unit Rates",
        "description": "Calculating rates per single unit (price per item, speed in km/h) and finding constant of proportionality.",
        "domain": "ratios",
        "tier": 5,
        "prerequisites": ["ratios"],
    },
    {
        "id": "proportions",
        "name": "Proportions",
        "description": "Solving proportional equations using cross-multiplication and scaling factors.",
        "domain": "ratios",
        "tier": 6,
        "prerequisites": ["unit_rates"],
    },
    {
        "id": "percentages",
        "name": "Percentages Basics",
        "description": "Expressing quantities as parts per hundred, connecting percentages, fractions, and decimals.",
        "domain": "percentages",
        "tier": 7,
        "prerequisites": ["proportions", "decimals_basics"],
    },
    {
        "id": "percentage_change",
        "name": "Percentage Change",
        "description": "Calculating markups, discounts, tax, percent increase and percent decrease in real-world contexts.",
        "domain": "percentages",
        "tier": 8,
        "prerequisites": ["percentages"],
    },
]

# 5 questions per concept = 50 questions total
# Difficulty: 1 to 5
# Type: recall, procedural, transfer
# Wrong answers tagged with pedagogical misconceptions
# Hints: 3 progressive levels
SEED_QUESTIONS: List[Dict[str, Any]] = [
    # ---------------- 1. fraction_basics ----------------
    {
        "id": "fb_1",
        "concept_id": "fraction_basics",
        "difficulty": 1,
        "type": "recall",
        "prompt": "In the fraction 3/8, what number represents the denominator, and what does it tell you?",
        "answer": "8; the total number of equal parts in the whole",
        "wrong_answers": [
            {"option": "3; the parts being considered", "misconception": "Confusing numerator with denominator"},
            {"option": "8; the number of parts remaining", "misconception": "Misinterpreting denominator as remainder"},
            {"option": "5; the difference between parts", "misconception": "Subtracting terms instead of recognizing whole"},
        ],
        "hints": [
            "Remember that 'denominator' comes from the Latin for 'naming' the unit size.",
            "The top number is the numerator (counting parts); the bottom number is the denominator.",
            "The bottom number is 8, which indicates that the whole is divided into 8 equal parts.",
        ],
    },
    {
        "id": "fb_2",
        "concept_id": "fraction_basics",
        "difficulty": 2,
        "type": "procedural",
        "prompt": "A chocolate bar is divided into 6 equal squares. If you eat 2 squares, what fraction of the bar remains?",
        "answer": "4/6",
        "wrong_answers": [
            {"option": "2/6", "misconception": "Reporting the consumed fraction rather than remaining"},
            {"option": "2/4", "misconception": "Creating a ratio of eaten to remaining rather than whole"},
            {"option": "4/4", "misconception": "Assuming the whole size changed"},
        ],
        "hints": [
            "Identify the whole: total squares = 6.",
            "Subtract the eaten squares (2) from the total squares (6) to find what remains.",
            "Remaining squares = 6 - 2 = 4, so the fraction is 4/6 (or 2/3).",
        ],
    },
    {
        "id": "fb_3",
        "concept_id": "fraction_basics",
        "difficulty": 3,
        "type": "procedural",
        "prompt": "Which fraction represents the point exactly three-quarters of the way from 0 to 1 on a number line?",
        "answer": "3/4",
        "wrong_answers": [
            {"option": "4/3", "misconception": "Inverting numerator and denominator"},
            {"option": "3/7", "misconception": "Adding numerator and denominator to create a new whole"},
            {"option": "1/4", "misconception": "Measuring distance from 1 instead of from 0"},
        ],
        "hints": [
            "Divide the interval from 0 to 1 into 4 equal segments.",
            "Count 3 segments starting from 0.",
            "Three out of four unit segments equals 3/4.",
        ],
    },
    {
        "id": "fb_4",
        "concept_id": "fraction_basics",
        "difficulty": 4,
        "type": "transfer",
        "prompt": "A carpenter cuts an 8-foot board into two pieces. One piece is 3/8 of the whole board. How many feet long is the other piece?",
        "answer": "5 feet",
        "wrong_answers": [
            {"option": "3 feet", "misconception": "Calculating the length of the first piece instead of the remaining piece"},
            {"option": "5/8 feet", "misconception": "Reporting the remaining fraction without multiplying by the board length"},
            {"option": "4 feet", "misconception": "Arbitrary estimation"},
        ],
        "hints": [
            "First find what fraction of the board remains after removing 3/8.",
            "The remaining fraction is 1 - 3/8 = 5/8 of the board.",
            "Multiply 5/8 by the 8-foot board length: (5/8) * 8 = 5 feet.",
        ],
    },
    {
        "id": "fb_5",
        "concept_id": "fraction_basics",
        "difficulty": 5,
        "type": "transfer",
        "prompt": "Container A is 2/5 full of water. Container B is identical in volume and is 3/10 full. If both are poured into an empty Container C of the same volume, what fraction of Container C will be filled?",
        "answer": "7/10",
        "wrong_answers": [
            {"option": "5/15", "misconception": "Adding numerators and adding denominators directly"},
            {"option": "5/10", "misconception": "Adding numerators without finding a common denominator"},
            {"option": "6/50", "misconception": "Multiplying fractions instead of adding"},
        ],
        "hints": [
            "You need to add the two fractions: 2/5 + 3/10.",
            "Convert 2/5 to tenths so both have the common denominator 10: 2/5 = 4/10.",
            "Add the numerators: 4/10 + 3/10 = 7/10.",
        ],
    },

    # ---------------- 2. equivalent_fractions ----------------
    {
        "id": "ef_1",
        "concept_id": "equivalent_fractions",
        "difficulty": 1,
        "type": "recall",
        "prompt": "What mathematical operation must you perform on both the numerator and denominator to create an equivalent fraction?",
        "answer": "Multiply or divide both by the same non-zero number",
        "wrong_answers": [
            {"option": "Add the same number to both", "misconception": "Additive misconception of fraction equivalence"},
            {"option": "Subtract the same number from both", "misconception": "Subtractive distortion"},
            {"option": "Square both numbers", "misconception": "Applying non-linear scaling"},
        ],
        "hints": [
            "Multiplying a quantity by 1 does not change its value.",
            "A fraction like 2/2 or 3/3 equals 1.",
            "Multiplying or dividing top and bottom by the same non-zero constant preserves the ratio.",
        ],
    },
    {
        "id": "ef_2",
        "concept_id": "equivalent_fractions",
        "difficulty": 2,
        "type": "procedural",
        "prompt": "Simplify the fraction 18/24 to its lowest terms.",
        "answer": "3/4",
        "wrong_answers": [
            {"option": "9/12", "misconception": "Incomplete reduction (divided only by 2)"},
            {"option": "6/8", "misconception": "Incomplete reduction (divided only by 3)"},
            {"option": "2/3", "misconception": "Incorrect common divisor estimation"},
        ],
        "hints": [
            "Find the greatest common factor (GCF) of 18 and 24.",
            "Factors of 18: 1, 2, 3, 6, 9, 18. Factors of 24: 1, 2, 3, 4, 6, 8, 12, 24. GCF is 6.",
            "Divide numerator and denominator by 6: 18÷6 = 3, 24÷6 = 4. Result: 3/4.",
        ],
    },
    {
        "id": "ef_3",
        "concept_id": "equivalent_fractions",
        "difficulty": 3,
        "type": "procedural",
        "prompt": "Find the missing value x that makes 4/7 = x/35 true.",
        "answer": "20",
        "wrong_answers": [
            {"option": "28", "misconception": "Adding 28 because 35 - 7 = 28"},
            {"option": "16", "misconception": "Multiplying by 4 instead of scaling factor 5"},
            {"option": "140", "misconception": "Multiplying 4 * 35 without dividing by 7"},
        ],
        "hints": [
            "Look at the relationship between denominators 7 and 35.",
            "Since 7 * 5 = 35, the scale factor is 5.",
            "Multiply the numerator 4 by the scale factor 5: 4 * 5 = 20.",
        ],
    },
    {
        "id": "ef_4",
        "concept_id": "equivalent_fractions",
        "difficulty": 4,
        "type": "transfer",
        "prompt": "In an election, Candidate Alpha received 12 out of 36 votes, while Candidate Beta received 15 out of 45 votes. Did Alpha and Beta receive the same share of the vote?",
        "answer": "Yes, both received exactly 1/3 of the vote",
        "wrong_answers": [
            {"option": "No, Beta received more because 15 > 12", "misconception": "Absolute count bias over proportional equivalence"},
            {"option": "No, Alpha received more because 36 is smaller", "misconception": "Inverse whole bias"},
            {"option": "Cannot be determined without knowing total registered voters", "misconception": "Failure to recognize self-contained ratio"},
        ],
        "hints": [
            "Simplify Candidate Alpha's fraction: 12/36.",
            "Simplify Candidate Beta's fraction: 15/45.",
            "12/36 = 1/3 and 15/45 = 1/3. Both shares are equivalent to 1/3.",
        ],
    },
    {
        "id": "ef_5",
        "concept_id": "equivalent_fractions",
        "difficulty": 5,
        "type": "transfer",
        "prompt": "A paint recipe requires blue and yellow pigments in the ratio 6:15. A painter wants to make 70 liters of this exact shade using equivalent proportions. How many liters of blue pigment are required?",
        "answer": "20 liters",
        "wrong_answers": [
            {"option": "28 liters", "misconception": "Applying 6/15 directly to 70 as a fraction of whole"},
            {"option": "30 liters", "misconception": "Assuming equal split"},
            {"option": "14 liters", "misconception": "Arithmetic division error in scale factor"},
        ],
        "hints": [
            "Simplify the ratio 6:15 by dividing by 3: the ratio is 2 parts blue to 5 parts yellow.",
            "Total parts in the mixture = 2 + 5 = 7 equal parts.",
            "Each part = 70 liters ÷ 7 = 10 liters. Blue required = 2 * 10 = 20 liters.",
        ],
    },

    # ---------------- 3. comparing_fractions ----------------
    {
        "id": "cf_1",
        "concept_id": "comparing_fractions",
        "difficulty": 1,
        "type": "recall",
        "prompt": "When two fractions have the same denominator (e.g. 3/7 and 5/7), which fraction is larger?",
        "answer": "The fraction with the greater numerator",
        "wrong_answers": [
            {"option": "The fraction with the smaller numerator", "misconception": "Confusing numerator logic with denominator logic"},
            {"option": "They are always equal if denominators match", "misconception": "Ignoring numerators entirely"},
            {"option": "The one closest to zero", "misconception": "Reversing magnitude"},
        ],
        "hints": [
            "The denominator defines the size of each slice.",
            "If the slices are the same size, having more slices means having more overall.",
            "5/7 is greater than 3/7 because 5 parts is more than 3 parts of the same size.",
        ],
    },
    {
        "id": "cf_2",
        "concept_id": "comparing_fractions",
        "difficulty": 2,
        "type": "procedural",
        "prompt": "Which inequality correctly compares 2/3 and 3/5?",
        "answer": "2/3 > 3/5",
        "wrong_answers": [
            {"option": "2/3 < 3/5", "misconception": "Thinking 3/5 is larger because 3 > 2 and 5 > 3"},
            {"option": "2/3 = 3/5", "misconception": "Assuming both are approximately one half"},
            {"option": "Cannot be compared because denominators differ", "misconception": "Lack of common denominator awareness"},
        ],
        "hints": [
            "Find a common denominator for 3 and 5, which is 15.",
            "Convert both: 2/3 = 10/15 and 3/5 = 9/15.",
            "Since 10/15 > 9/15, 2/3 > 3/5.",
        ],
    },
    {
        "id": "cf_3",
        "concept_id": "comparing_fractions",
        "difficulty": 3,
        "type": "procedural",
        "prompt": "Order the fractions from least to greatest: 1/2, 3/8, 5/6.",
        "answer": "3/8, 1/2, 5/6",
        "wrong_answers": [
            {"option": "1/2, 3/8, 5/6", "misconception": "Ordering by numerator size only"},
            {"option": "5/6, 1/2, 3/8", "misconception": "Ordering greatest to least"},
            {"option": "3/8, 5/6, 1/2", "misconception": "Misjudging 1/2 against 5/6"},
        ],
        "hints": [
            "Use the benchmark fraction 1/2: 3/8 is less than 1/2 (since 4/8 = 1/2).",
            "5/6 is greater than 1/2 (since 3/6 = 1/2).",
            "Therefore: 3/8 < 1/2 < 5/6.",
        ],
    },
    {
        "id": "cf_4",
        "concept_id": "comparing_fractions",
        "difficulty": 4,
        "type": "transfer",
        "prompt": "Runner X completed 7/12 of a marathon before cramping. Runner Y completed 5/8 of the marathon. Who ran farther?",
        "answer": "Runner Y ran farther",
        "wrong_answers": [
            {"option": "Runner X ran farther", "misconception": "Comparing numerators directly: 7 > 5 without matching denominators"},
            {"option": "Both ran exactly the same distance", "misconception": "Approximating both as slightly over half"},
            {"option": "Runner X, because 12 is greater than 8", "misconception": "Associating larger denominator with larger value"},
        ],
        "hints": [
            "Find the lowest common denominator for 12 and 8, which is 24.",
            "Convert Runner X: 7/12 = 14/24. Convert Runner Y: 5/8 = 15/24.",
            "15/24 > 14/24, so Runner Y (5/8) ran farther.",
        ],
    },
    {
        "id": "cf_5",
        "concept_id": "comparing_fractions",
        "difficulty": 5,
        "type": "transfer",
        "prompt": "Solar Battery Alpha discharges to 4/9 capacity in 4 hours. Battery Beta discharges to 5/11 capacity in the same time. Which battery retained more charge?",
        "answer": "Battery Beta (5/11)",
        "wrong_answers": [
            {"option": "Battery Alpha (4/9)", "misconception": "Cross multiplying in reverse: 4*11=44 vs 9*5=45 and misassigning"},
            {"option": "Both retained equal charge", "misconception": "Rough rounding error"},
            {"option": "Battery Alpha, because 9 is smaller than 11", "misconception": "Inverted denominator heuristic"},
        ],
        "hints": [
            "Compare 4/9 and 5/11 using cross-multiplication: 4 * 11 vs 5 * 9.",
            "4 * 11 = 44 (for 4/9); 9 * 5 = 45 (for 5/11).",
            "Since 45 > 44, 5/11 > 4/9. Battery Beta retained more charge.",
        ],
    },

    # ---------------- 4. fraction_operations ----------------
    {
        "id": "fo_1",
        "concept_id": "fraction_operations",
        "difficulty": 1,
        "type": "recall",
        "prompt": "When multiplying two fractions like (a/b) * (c/d), how do you calculate the result?",
        "answer": "Multiply numerators together, and multiply denominators together: (a*c)/(b*d)",
        "wrong_answers": [
            {"option": "Cross-multiply: (a*d)/(b*c)", "misconception": "Confusing fraction multiplication with division/proportions"},
            {"option": "Find a common denominator first, then multiply only numerators", "misconception": "Over-applying addition rules to multiplication"},
            {"option": "Add the numerators and multiply the denominators", "misconception": "Mixing operational rules"},
        ],
        "hints": [
            "Unlike addition, multiplication does not require a common denominator.",
            "Top multiplies by top; bottom multiplies by bottom.",
            "(a/b) * (c/d) = (a * c) / (b * d).",
        ],
    },
    {
        "id": "fo_2",
        "concept_id": "fraction_operations",
        "difficulty": 2,
        "type": "procedural",
        "prompt": "Calculate 3/4 + 1/6 in simplest form.",
        "answer": "11/12",
        "wrong_answers": [
            {"option": "4/10", "misconception": "Adding numerators and adding denominators: (3+1)/(4+6)"},
            {"option": "4/12", "misconception": "Adding numerators without scaling to common denominator"},
            {"option": "10/12", "misconception": "Arithmetic addition slip"},
        ],
        "hints": [
            "Find the least common multiple of 4 and 6: LCM is 12.",
            "Convert fractions: 3/4 = 9/12 and 1/6 = 2/12.",
            "Add the numerators: 9/12 + 2/12 = 11/12.",
        ],
    },
    {
        "id": "fo_3",
        "concept_id": "fraction_operations",
        "difficulty": 3,
        "type": "procedural",
        "prompt": "Calculate 5/8 divided by 3/4 in simplest form.",
        "answer": "5/6",
        "wrong_answers": [
            {"option": "15/32", "misconception": "Multiplying directly instead of multiplying by reciprocal"},
            {"option": "6/5", "misconception": "Inverting the dividend rather than the divisor"},
            {"option": "20/24", "misconception": "Failing to simplify 20/24 to lowest terms"},
        ],
        "hints": [
            "Dividing by a fraction is equivalent to multiplying by its reciprocal.",
            "Reciprocal of 3/4 is 4/3.",
            "Calculate: (5/8) * (4/3) = 20/24. Divide top and bottom by 4 to get 5/6.",
        ],
    },
    {
        "id": "fo_4",
        "concept_id": "fraction_operations",
        "difficulty": 4,
        "type": "transfer",
        "prompt": "A chef has 4 and 1/2 pounds of dough. Each gourmet roll requires 3/8 pound of dough. How many full rolls can the chef prepare?",
        "answer": "12 rolls",
        "wrong_answers": [
            {"option": "10 rolls", "misconception": "Rounding down due to division estimation error"},
            {"option": "16 rolls", "misconception": "Multiplying 4 * 4 instead of dividing properly"},
            {"option": "1 and 11/16 rolls", "misconception": "Multiplying 9/2 by 3/8 instead of dividing"},
        ],
        "hints": [
            "Convert 4 and 1/2 to an improper fraction: 9/2.",
            "Divide total dough by portion size: (9/2) ÷ (3/8).",
            "(9/2) * (8/3) = 72/6 = 12 rolls.",
        ],
    },
    {
        "id": "fo_5",
        "concept_id": "fraction_operations",
        "difficulty": 5,
        "type": "transfer",
        "prompt": "A community garden allocates 2/3 of its land to vegetables. Of that vegetable section, 3/5 is dedicated to heirloom tomatoes. If the total garden area is 300 square meters, how many square meters are heirloom tomatoes?",
        "answer": "120 square meters",
        "wrong_answers": [
            {"option": "180 square meters", "misconception": "Calculating total vegetable area without applying the 3/5 fraction"},
            {"option": "100 square meters", "misconception": "Assuming 1/3 of total area"},
            {"option": "250 square meters", "misconception": "Adding fractions instead of multiplying: 2/3 + 3/5"},
        ],
        "hints": [
            "Find the fraction of the total garden dedicated to tomatoes: (2/3) * (3/5).",
            "(2 * 3) / (3 * 5) = 6/15 = 2/5 of the total garden.",
            "Multiply by 300 sq m: (2/5) * 300 = 120 square meters.",
        ],
    },

    # ---------------- 5. decimals_basics ----------------
    {
        "id": "db_1",
        "concept_id": "decimals_basics",
        "difficulty": 1,
        "type": "recall",
        "prompt": "In the decimal number 0.47, what place value does the digit 7 occupy?",
        "answer": "Hundredths",
        "wrong_answers": [
            {"option": "Tenths", "misconception": "Confusing first and second decimal positions"},
            {"option": "Tens", "misconception": "Mirroring whole number places across decimal point"},
            {"option": "Thousandths", "misconception": "Skipping place values"},
        ],
        "hints": [
            "The first digit to the right of the decimal point is the tenths place.",
            "The second digit to the right is the hundredths place.",
            "4 is tenths, 7 is hundredths.",
        ],
    },
    {
        "id": "db_2",
        "concept_id": "decimals_basics",
        "difficulty": 2,
        "type": "procedural",
        "prompt": "Convert the fraction 3/5 to a decimal.",
        "answer": "0.6",
        "wrong_answers": [
            {"option": "0.35", "misconception": "Concatenating numerator and denominator directly into decimal"},
            {"option": "0.3", "misconception": "Taking numerator only"},
            {"option": "1.66", "misconception": "Dividing denominator by numerator: 5 ÷ 3"},
        ],
        "hints": [
            "Convert 3/5 to tenths: 3/5 = 6/10.",
            "6 tenths is written as 0.6.",
            "Alternatively, divide 3 by 5: 3.0 ÷ 5 = 0.6.",
        ],
    },
    {
        "id": "db_3",
        "concept_id": "decimals_basics",
        "difficulty": 3,
        "type": "procedural",
        "prompt": "Convert the decimal 0.375 into a simplified fraction.",
        "answer": "3/8",
        "wrong_answers": [
            {"option": "375/100", "misconception": "Incorrect decimal denominator (100 instead of 1000)"},
            {"option": "3/7", "misconception": "Guessing based on visible digits"},
            {"option": "1/4", "misconception": "Approximating without simplifying"},
        ],
        "hints": [
            "0.375 has three decimal places, which represents 375/1000.",
            "Find the greatest common factor of 375 and 1000, which is 125.",
            "375 ÷ 125 = 3; 1000 ÷ 125 = 8. Result is 3/8.",
        ],
    },
    {
        "id": "db_4",
        "concept_id": "decimals_basics",
        "difficulty": 4,
        "type": "transfer",
        "prompt": "A precision scale reads 0.125 kg for a single bracket. A shipping crate can carry at most 10 kg. What is the maximum number of brackets the crate can hold?",
        "answer": "80 brackets",
        "wrong_answers": [
            {"option": "125 brackets", "misconception": "Multiplying 10 by the digits 12.5"},
            {"option": "8 brackets", "misconception": "Decimal place error by factor of 10"},
            {"option": "100 brackets", "misconception": "Rough estimation ignoring bracket weight"},
        ],
        "hints": [
            "Notice that 0.125 is equivalent to 1/8 kg.",
            "Dividing 10 by 1/8 is equivalent to 10 * 8.",
            "10 ÷ 0.125 = 80 brackets.",
        ],
    },
    {
        "id": "db_5",
        "concept_id": "decimals_basics",
        "difficulty": 5,
        "type": "transfer",
        "prompt": "An audio file of 1.4 gigabytes downloads at an average speed of 0.035 gigabytes per second. How many seconds will the download take?",
        "answer": "40 seconds",
        "wrong_answers": [
            {"option": "4 seconds", "misconception": "Decimal shift error by 10"},
            {"option": "400 seconds", "misconception": "Decimal shift error by 100"},
            {"option": "49 seconds", "misconception": "Multiplying 1.4 * 0.035"},
        ],
        "hints": [
            "Time = Total size ÷ Speed = 1.4 ÷ 0.035.",
            "Shift decimal points 3 places to the right: 1400 ÷ 35.",
            "1400 ÷ 35 = 40 seconds.",
        ],
    },

    # ---------------- 6. ratios ----------------
    {
        "id": "r_1",
        "concept_id": "ratios",
        "difficulty": 1,
        "type": "recall",
        "prompt": "In a classroom there are 12 boys and 16 girls. What is the simplified ratio of boys to girls?",
        "answer": "3:4",
        "wrong_answers": [
            {"option": "4:3", "misconception": "Reversing ratio terms (girls to boys instead of boys to girls)"},
            {"option": "3:7", "misconception": "Reporting part-to-whole ratio instead of part-to-part"},
            {"option": "12:28", "misconception": "Comparing boys to total class"},
        ],
        "hints": [
            "Write the ratio in the requested order: boys (12) to girls (16).",
            "Divide both terms by their greatest common factor (4).",
            "12 ÷ 4 = 3, 16 ÷ 4 = 4. Result: 3:4.",
        ],
    },
    {
        "id": "r_2",
        "concept_id": "ratios",
        "difficulty": 2,
        "type": "procedural",
        "prompt": "A fruit punch recipe mixes pineapple juice and orange juice in a ratio of 2:5. If you use 15 cups of orange juice, how many cups of pineapple juice are needed?",
        "answer": "6 cups",
        "wrong_answers": [
            {"option": "10 cups", "misconception": "Adding 5 to pineapple juice because 15 - 5 = 10"},
            {"option": "37.5 cups", "misconception": "Inverting the ratio: 15 * (5/2)"},
            {"option": "30 cups", "misconception": "Multiplying 15 by 2 without dividing by 5"},
        ],
        "hints": [
            "Set up the proportion: (Pineapple / Orange) = 2 / 5.",
            "Find the multiplier: 5 * 3 = 15 cups of orange juice.",
            "Multiply pineapple parts by 3: 2 * 3 = 6 cups.",
        ],
    },
    {
        "id": "r_3",
        "concept_id": "ratios",
        "difficulty": 3,
        "type": "procedural",
        "prompt": "A triangle's perimeter is 48 cm, and its side lengths are in the ratio 3:4:5. What is the length of the longest side?",
        "answer": "20 cm",
        "wrong_answers": [
            {"option": "16 cm", "misconception": "Calculating the middle side (4 parts) instead of the longest"},
            {"option": "12 cm", "misconception": "Calculating the shortest side (3 parts)"},
            {"option": "24 cm", "misconception": "Halving the perimeter"},
        ],
        "hints": [
            "Sum the ratio parts: 3 + 4 + 5 = 12 total parts.",
            "Find the value of one part: 48 cm ÷ 12 = 4 cm per part.",
            "Multiply by the longest side (5 parts): 5 * 4 cm = 20 cm.",
        ],
    },
    {
        "id": "r_4",
        "concept_id": "ratios",
        "difficulty": 4,
        "type": "transfer",
        "prompt": "In an aquarium, the ratio of clownfish to angelfish is 4:7. If 6 new clownfish are added, the ratio becomes 1:1. How many angelfish are in the aquarium?",
        "answer": "14 angelfish",
        "wrong_answers": [
            {"option": "8 angelfish", "misconception": "Reporting initial clownfish count"},
            {"option": "21 angelfish", "misconception": "Multiplying by wrong unit scale"},
            {"option": "12 angelfish", "misconception": "Arithmetic difference misattribution"},
        ],
        "hints": [
            "Let clownfish = 4x and angelfish = 7x.",
            "When 6 clownfish are added, 4x + 6 = 7x (since the ratio is 1:1).",
            "3x = 6, so x = 2. Angelfish = 7 * 2 = 14.",
        ],
    },
    {
        "id": "r_5",
        "concept_id": "ratios",
        "difficulty": 5,
        "type": "transfer",
        "prompt": "Two alloy ingots have copper-to-zinc ratios of 2:3 and 4:1. If equal weights of both ingots are melted together, what is the copper-to-zinc ratio of the resulting alloy?",
        "answer": "6:4 (or 3:2)",
        "wrong_answers": [
            {"option": "6:4 directly added without checking whole weights", "misconception": "Adding ratio components without establishing common total parts"},
            {"option": "8:3", "misconception": "Multiplying terms across alloys"},
            {"option": "1:1", "misconception": "Assuming equal halves produce balanced ratio"},
        ],
        "hints": [
            "Both ratios have 5 total parts: Ingot 1 has 2/5 copper and 3/5 zinc; Ingot 2 has 4/5 copper and 1/5 zinc.",
            "Add copper fractions: 2/5 + 4/5 = 6/5 copper. Add zinc fractions: 3/5 + 1/5 = 4/5 zinc.",
            "The ratio of copper to zinc is 6:4, which simplifies to 3:2.",
        ],
    },

    # ---------------- 7. unit_rates ----------------
    {
        "id": "ur_1",
        "concept_id": "unit_rates",
        "difficulty": 1,
        "type": "recall",
        "prompt": "What distinguishes a unit rate from a general rate?",
        "answer": "A unit rate always has a denominator of 1 (quantity per single unit)",
        "wrong_answers": [
            {"option": "A unit rate is always measured in metric units", "misconception": "Confusing unit with measurement standard"},
            {"option": "A unit rate can only measure price or currency", "misconception": "Domain restriction misconception"},
            {"option": "A unit rate has no units attached", "misconception": "Thinking unit means dimensionless"},
        ],
        "hints": [
            "Consider phrases like 'miles per hour' or 'dollars per pound'.",
            "'Unit' refers to a single individual item (value of 1).",
            "A unit rate compares a quantity to exactly one unit of another quantity.",
        ],
    },
    {
        "id": "ur_2",
        "concept_id": "unit_rates",
        "difficulty": 2,
        "type": "procedural",
        "prompt": "A car travels 240 miles on 8 gallons of gasoline. What is the car's fuel efficiency in miles per gallon?",
        "answer": "30 miles per gallon",
        "wrong_answers": [
            {"option": "24 miles per gallon", "misconception": "Arithmetic division error"},
            {"option": "0.033 gallons per mile", "misconception": "Inverting the rate (gallons per mile instead of miles per gallon)"},
            {"option": "1920 miles per gallon", "misconception": "Multiplying 240 * 8 instead of dividing"},
        ],
        "hints": [
            "Set up the rate: Miles ÷ Gallons.",
            "Calculate: 240 ÷ 8.",
            "240 ÷ 8 = 30 miles per gallon.",
        ],
    },
    {
        "id": "ur_3",
        "concept_id": "unit_rates",
        "difficulty": 3,
        "type": "procedural",
        "prompt": "Brand A sells 18 oz of cereal for $4.50. Brand B sells 24 oz of cereal for $5.52. Which brand has the lower price per ounce?",
        "answer": "Brand B ($0.23/oz vs Brand A $0.25/oz)",
        "wrong_answers": [
            {"option": "Brand A ($0.25/oz)", "misconception": "Judging Brand A as cheaper because its total price $4.50 is lower"},
            {"option": "Both have the identical unit price", "misconception": "Rough rounding error"},
            {"option": "Brand A, because 18 oz is smaller", "misconception": "Smaller quantity bias"},
        ],
        "hints": [
            "Compute Brand A unit price: $4.50 ÷ 18 oz = $0.25 per oz.",
            "Compute Brand B unit price: $5.52 ÷ 24 oz = $0.23 per oz.",
            "$0.23 < $0.25, so Brand B has the lower unit price.",
        ],
    },
    {
        "id": "ur_4",
        "concept_id": "unit_rates",
        "difficulty": 4,
        "type": "transfer",
        "prompt": "A continuous inkjet printer produces 150 colored brochures in 4 minutes. At this constant rate, how many brochures can it print in 14 minutes?",
        "answer": "525 brochures",
        "wrong_answers": [
            {"option": "450 brochures", "misconception": "Underestimating scale factor as 3 instead of 3.5"},
            {"option": "600 brochures", "misconception": "Overestimating multiplier as 4"},
            {"option": "37.5 brochures", "misconception": "Reporting the unit rate without multiplying by 14"},
        ],
        "hints": [
            "Find the unit rate: 150 brochures ÷ 4 minutes = 37.5 brochures per minute.",
            "Multiply the unit rate by the new time: 37.5 * 14.",
            "37.5 * 14 = 525 brochures.",
        ],
    },
    {
        "id": "ur_5",
        "concept_id": "unit_rates",
        "difficulty": 5,
        "type": "transfer",
        "prompt": "Pipe A fills a reservoir at a rate of 120 liters every 5 minutes. Pipe B drains the reservoir at 70 liters every 4 minutes. If both pipes are opened simultaneously, what is the net rate of water accumulation in liters per minute?",
        "answer": "6.5 liters per minute",
        "wrong_answers": [
            {"option": "50 liters per minute", "misconception": "Subtracting 120 - 70 without normalizing to per-minute rates"},
            {"option": "41.5 liters per minute", "misconception": "Adding the rates instead of subtracting inflow and outflow"},
            {"option": "10 liters per minute", "misconception": "Estimation error"},
        ],
        "hints": [
            "Calculate Pipe A inflow unit rate: 120 ÷ 5 = 24 liters per minute.",
            "Calculate Pipe B outflow unit rate: 70 ÷ 4 = 17.5 liters per minute.",
            "Net rate = Inflow - Outflow = 24 - 17.5 = 6.5 liters per minute.",
        ],
    },

    # ---------------- 8. proportions ----------------
    {
        "id": "pr_1",
        "concept_id": "proportions",
        "difficulty": 1,
        "type": "recall",
        "prompt": "What does a mathematical proportion assert?",
        "answer": "An equation stating that two ratios or rates are strictly equal",
        "wrong_answers": [
            {"option": "An equation showing that one number is always larger than another", "misconception": "Confusing proportion with inequality"},
            {"option": "The sum of several fractions", "misconception": "Confusing proportion with summation"},
            {"option": "A percentage value between 0 and 100", "misconception": "Confusing proportion with percentage representation"},
        ],
        "hints": [
            "Proportions have an equals sign between two fractions: a/b = c/d.",
            "The term comes from having proportional balance.",
            "A proportion states that two ratios are equal.",
        ],
    },
    {
        "id": "pr_2",
        "concept_id": "proportions",
        "difficulty": 2,
        "type": "procedural",
        "prompt": "Solve for x in the proportion: 3 / 8 = 15 / x.",
        "answer": "40",
        "wrong_answers": [
            {"option": "20", "misconception": "Adding 12 instead of multiplying by scale factor 5"},
            {"option": "24", "misconception": "Multiplying 8 by 3 instead of 5"},
            {"option": "45", "misconception": "Multiplying 15 by 3"},
        ],
        "hints": [
            "Notice the numerator scale: 3 * 5 = 15.",
            "Multiply the denominator by the same factor: 8 * 5 = 40.",
            "Alternatively, cross multiply: 3x = 8 * 15 = 120 => x = 40.",
        ],
    },
    {
        "id": "pr_3",
        "concept_id": "proportions",
        "difficulty": 3,
        "type": "procedural",
        "prompt": "Solve for y: (y + 2) / 6 = 5 / 3.",
        "answer": "8",
        "wrong_answers": [
            {"option": "10", "misconception": "Solving for (y + 2) = 10 but forgetting to subtract 2"},
            {"option": "12", "misconception": "Adding 2 instead of subtracting: 10 + 2"},
            {"option": "6", "misconception": "Arithmetic division slip"},
        ],
        "hints": [
            "Cross-multiply: 3 * (y + 2) = 6 * 5.",
            "3y + 6 = 30.",
            "3y = 24, so y = 8.",
        ],
    },
    {
        "id": "pr_4",
        "concept_id": "proportions",
        "difficulty": 4,
        "type": "transfer",
        "prompt": "On an architectural map, 2 centimeters represents 15 meters in reality. If a building is 45 meters long in reality, how long is its representation on the blueprint?",
        "answer": "6 centimeters",
        "wrong_answers": [
            {"option": "4.5 centimeters", "misconception": "Dividing 45 by 10 without scaling with 2 cm"},
            {"option": "3 centimeters", "misconception": "Dividing 45 by 15 but forgetting to multiply by 2"},
            {"option": "30 centimeters", "misconception": "Scale inversion error"},
        ],
        "hints": [
            "Set up the proportion: (2 cm / 15 m) = (x cm / 45 m).",
            "Notice that 45 m is 3 times 15 m (scale factor = 3).",
            "x = 2 cm * 3 = 6 centimeters.",
        ],
    },
    {
        "id": "pr_5",
        "concept_id": "proportions",
        "difficulty": 5,
        "type": "transfer",
        "prompt": "At noon, a 1.8-meter-tall person casts a shadow that is 1.2 meters long. At the exact same moment, a nearby cell tower casts a shadow that is 28 meters long. What is the height of the cell tower?",
        "answer": "42 meters",
        "wrong_answers": [
            {"option": "36 meters", "misconception": "Subtracting shadow difference instead of scaling proportionally"},
            {"option": "18.67 meters", "misconception": "Inverting the ratio: 28 * (1.2 / 1.8)"},
            {"option": "50.4 meters", "misconception": "Multiplying 28 * 1.8 without dividing by 1.2"},
        ],
        "hints": [
            "Set up similar triangles proportion: (Height / Shadow) = 1.8 / 1.2.",
            "Tower Height / 28 = 1.8 / 1.2 = 1.5.",
            "Tower Height = 28 * 1.5 = 42 meters.",
        ],
    },

    # ---------------- 9. percentages ----------------
    {
        "id": "pct_1",
        "concept_id": "percentages",
        "difficulty": 1,
        "type": "recall",
        "prompt": "What does the symbol '%' literally mean from its Latin root 'per centum'?",
        "answer": "Per one hundred (out of every 100)",
        "wrong_answers": [
            {"option": "Per thousand", "misconception": "Confusing percent with per mille"},
            {"option": "A number greater than 1", "misconception": "Misunderstanding fraction representation"},
            {"option": "Divided by 10", "misconception": "Decade order of magnitude confusion"},
        ],
        "hints": [
            "Think of a century (100 years) or a cent (1/100 of a dollar).",
            "'Cent' stands for 100.",
            "Percent means 'per hundred' or divided by 100.",
        ],
    },
    {
        "id": "pct_2",
        "concept_id": "percentages",
        "difficulty": 2,
        "type": "procedural",
        "prompt": "Convert 7/20 into a percentage.",
        "answer": "35%",
        "wrong_answers": [
            {"option": "7%", "misconception": "Taking the numerator directly as the percentage"},
            {"option": "14%", "misconception": "Multiplying by 2 instead of 5"},
            {"option": "70%", "misconception": "Assuming denominator is 10 instead of 20"},
        ],
        "hints": [
            "Convert the denominator to 100: multiply 20 by 5.",
            "Multiply numerator by 5 as well: 7 * 5 = 35.",
            "35/100 = 35%.",
        ],
    },
    {
        "id": "pct_3",
        "concept_id": "percentages",
        "difficulty": 3,
        "type": "procedural",
        "prompt": "What is 15% of $80?",
        "answer": "$12",
        "wrong_answers": [
            {"option": "$15", "misconception": "Confusing percentage rate with dollar amount"},
            {"option": "$8", "misconception": "Calculating 10% instead of 15%"},
            {"option": "$5.33", "misconception": "Dividing 80 by 15"},
        ],
        "hints": [
            "Find 10% of $80 first: 80 ÷ 10 = $8.",
            "5% is half of 10%: $8 ÷ 2 = $4.",
            "Add 10% + 5%: $8 + $4 = $12.",
        ],
    },
    {
        "id": "pct_4",
        "concept_id": "percentages",
        "difficulty": 4,
        "type": "transfer",
        "prompt": "In an exam of 75 questions, a student answered 60 correctly. What percentage of questions did the student answer correctly?",
        "answer": "80%",
        "wrong_answers": [
            {"option": "60%", "misconception": "Confusing raw score with percentage"},
            {"option": "75%", "misconception": "Using total question count as percentage"},
            {"option": "85%", "misconception": "Arithmetic estimation error"},
        ],
        "hints": [
            "Set up the fraction: 60 / 75.",
            "Simplify by dividing top and bottom by 15: 60 ÷ 15 = 4; 75 ÷ 15 = 5 (4/5).",
            "Convert 4/5 to percent: 4/5 * 100% = 80%.",
        ],
    },
    {
        "id": "pct_5",
        "concept_id": "percentages",
        "difficulty": 5,
        "type": "transfer",
        "prompt": "A sample contains 40 grams of salt dissolved in 160 grams of pure water. What is the percentage concentration of salt in the entire saline solution?",
        "answer": "20%",
        "wrong_answers": [
            {"option": "25%", "misconception": "Dividing solute by solvent (40/160) instead of total solution mass (40/200)"},
            {"option": "40%", "misconception": "Using raw solute mass as percentage"},
            {"option": "16%", "misconception": "Inverse fraction error"},
        ],
        "hints": [
            "Concentration = Solute mass ÷ Total solution mass.",
            "Total mass = 40 g salt + 160 g water = 200 grams.",
            "Percentage = (40 / 200) * 100% = 20%.",
        ],
    },

    # ---------------- 10. percentage_change ----------------
    {
        "id": "pc_1",
        "concept_id": "percentage_change",
        "difficulty": 1,
        "type": "recall",
        "prompt": "What is the standard formula for calculating percentage change?",
        "answer": "[(New Value - Original Value) / Original Value] * 100%",
        "wrong_answers": [
            {"option": "[(New Value - Original Value) / New Value] * 100%", "misconception": "Dividing by the new value instead of original reference baseline"},
            {"option": "(New Value / Original Value) * 100%", "misconception": "Calculating ratio without subtracting base 100%"},
            {"option": "(Original Value - New Value) * 100%", "misconception": "Reporting raw difference without dividing by baseline"},
        ],
        "hints": [
            "Percentage change always compares the delta against where you started.",
            "The denominator is the initial (original) quantity.",
            "[(New - Original) / Original] * 100%.",
        ],
    },
    {
        "id": "pc_2",
        "concept_id": "percentage_change",
        "difficulty": 2,
        "type": "procedural",
        "prompt": "The price of a hoodie increases from $50 to $65. What is the percentage increase?",
        "answer": "30%",
        "wrong_answers": [
            {"option": "$15", "misconception": "Reporting dollar change instead of percentage change"},
            {"option": "23%", "misconception": "Dividing by new price 65 ($15/$65 = 23%) instead of original 50"},
            {"option": "15%", "misconception": "Assuming $15 directly translates to 15%"},
        ],
        "hints": [
            "Find the dollar increase: $65 - $50 = $15.",
            "Divide by the original price: 15 ÷ 50 = 0.30.",
            "Multiply by 100%: 0.30 * 100% = 30%.",
        ],
    },
    {
        "id": "pc_3",
        "concept_id": "percentage_change",
        "difficulty": 3,
        "type": "procedural",
        "prompt": "A laptop originally priced at $800 is on sale for 25% off. What is the sale price?",
        "answer": "$600",
        "wrong_answers": [
            {"option": "$200", "misconception": "Reporting the discount amount instead of the final sale price"},
            {"option": "$650", "misconception": "Incorrect discount calculation"},
            {"option": "$775", "misconception": "Subtracting $25 instead of 25%"},
        ],
        "hints": [
            "Calculate 25% of $800: (1/4) * 800 = $200 discount.",
            "Subtract the discount from the original price: $800 - $200.",
            "Sale price is $600 (or 75% of $800).",
        ],
    },
    {
        "id": "pc_4",
        "concept_id": "percentage_change",
        "difficulty": 4,
        "type": "transfer",
        "prompt": "A retailer marks up a pair of shoes by 40% above wholesale cost, and later offers a 20% discount on that retail price during a holiday sale. What is the overall percentage gain above the wholesale cost?",
        "answer": "12% gain",
        "wrong_answers": [
            {"option": "20% gain", "misconception": "Simply subtracting percentages: 40% - 20% = 20% (additive fallacy)"},
            {"option": "28% gain", "misconception": "Arithmetic compounding mistake"},
            {"option": "No change (0%)", "misconception": "Believing markups and discounts cancel symmetrically"},
        ],
        "hints": [
            "Let the wholesale cost be $100 for convenience.",
            "A 40% markup gives a retail price of $100 * 1.40 = $140.",
            "A 20% discount on $140 reduces price by $28 ($140 - $28 = $112). Overall gain above $100 is 12%.",
        ],
    },
    {
        "id": "pc_5",
        "concept_id": "percentage_change",
        "difficulty": 5,
        "type": "transfer",
        "prompt": "Company revenue was $200,000 in Year 1. It dropped by 25% in Year 2 due to supply constraints, but grew by 40% in Year 3. What was the revenue at the end of Year 3?",
        "answer": "$210,000",
        "wrong_answers": [
            {"option": "$230,000", "misconception": "Applying net 15% (40% - 25%) directly to original $200k"},
            {"option": "$200,000", "misconception": "Assuming percentages returned to baseline"},
            {"option": "$180,000", "misconception": "Order-of-operations miscalculation"},
        ],
        "hints": [
            "Calculate Year 2 revenue after 25% drop: $200,000 * 0.75 = $150,000.",
            "Calculate Year 3 revenue after 40% growth on Year 2: $150,000 * 1.40.",
            "$150,000 * 1.40 = $210,000.",
        ],
    },
]
